/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IAntisnipe, IAntisnipeInterface } from "../IAntisnipe";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "assureCanTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IAntisnipe__factory {
  static readonly abi = _abi;
  static createInterface(): IAntisnipeInterface {
    return new utils.Interface(_abi) as IAntisnipeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAntisnipe {
    return new Contract(address, _abi, signerOrProvider) as IAntisnipe;
  }
}
