/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface AntisnipeMockInterface extends ethers.utils.Interface {
  functions: {
    "assureCanTransfer(address,address,address,uint256)": FunctionFragment;
    "lastAmount()": FunctionFragment;
    "lastFrom()": FunctionFragment;
    "lastSender()": FunctionFragment;
    "lastTo()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "assureCanTransfer",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lastAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lastFrom", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lastSender",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lastTo", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "assureCanTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lastAmount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lastFrom", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lastSender", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lastTo", data: BytesLike): Result;

  events: {};
}

export class AntisnipeMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: AntisnipeMockInterface;

  functions: {
    assureCanTransfer(
      sender: string,
      from: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    lastAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    lastFrom(overrides?: CallOverrides): Promise<[string]>;

    lastSender(overrides?: CallOverrides): Promise<[string]>;

    lastTo(overrides?: CallOverrides): Promise<[string]>;
  };

  assureCanTransfer(
    sender: string,
    from: string,
    to: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  lastAmount(overrides?: CallOverrides): Promise<BigNumber>;

  lastFrom(overrides?: CallOverrides): Promise<string>;

  lastSender(overrides?: CallOverrides): Promise<string>;

  lastTo(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    assureCanTransfer(
      sender: string,
      from: string,
      to: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    lastAmount(overrides?: CallOverrides): Promise<BigNumber>;

    lastFrom(overrides?: CallOverrides): Promise<string>;

    lastSender(overrides?: CallOverrides): Promise<string>;

    lastTo(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    assureCanTransfer(
      sender: string,
      from: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    lastAmount(overrides?: CallOverrides): Promise<BigNumber>;

    lastFrom(overrides?: CallOverrides): Promise<BigNumber>;

    lastSender(overrides?: CallOverrides): Promise<BigNumber>;

    lastTo(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    assureCanTransfer(
      sender: string,
      from: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    lastAmount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lastFrom(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lastSender(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lastTo(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
